== Spring Cloud Stream Python App Starters
:imagesdir: ./images


Spring Cloud Stream App Starters for integrating with Python

=== Provisioning Python Resources

Each of these applications in the Python family include configuration properties that specify Python script locations and directories.
These properties use Spring's http://docs.spring.io/spring/docs/current/spring-framework-reference/html/resources.html[Resource] abstraction.
Python script and directory locations reference to a local file  or URL resources (e.g. http).

Classpath resources are intentionally not supported as it would require a Python developer to package Python scripts
in the jar. If you provide a `git.url` to a repository, the application will clone the repository to the local file system during initialization and load scripts from there.


For more information on the available Spring Cloud Stream apps for Python, see the following pages.

include::spring-cloud-starter-stream-processor-python-http/README.adoc[]

include::spring-cloud-starter-stream-processor-python-jython/README.adoc[]

