# spring-cloud-stream-app-starters-python
:imagesdir: ./images


Spring Cloud Stream App Starters for integrating with Python

## Accessing Python Resources

Each of these applications in the Python family include configuration properties that specify Python script locations and directories. These properties use Spring's http://docs.spring.io/spring/docs/current/spring-framework-reference/html/resources.html[Resource] abstraction.  Python script and directory locations reference to a local file  or URL resources (e.g. http). 

Classpath resources are intentionally not supported as it would require a Python developer to package Pyhton scripts in the jar. 
If you provide a `git.url` to a repository, the application will clone the repository to the local file system during initialization and load scripts from there.  For local file system scripts (including a Git clone), if `requirements.txt` exists in the base directory, the application will `pip install` any Python dependencies. If you are running on Cloud Foundry, you need to use the link:docs/JavaPythonBuilPpack[Java Python buildpack].

[[NOTE]]
----
Conda apps require prior Conda to be installed on the local host. 
When running on Cloud Foundry, the Java Python buildpack will install the Conda environment per `environment.yml`.  
----

For more information on the available Spring Cloud Stream apps for Python, see the following pages.

## Python Http Processor
include::spring-cloud-starter-stream-processor-python-http/README.adoc[]

## Jython Processor
include::spring-cloud-starter-stream-processor-python-jython/README.adoc[]

# Python Local Processor

## Python Local Processor
include::spring-cloud-starter-stream-processor-python-local/README.adoc[]

## Python Local Sink
include::spring-cloud-starter-stream-sink-python-local/README.adoc[]


## Docker Images 
Use one of the of the java-python images https://hub.docker.com/u/korekontrol/[here],
